# Generated by Django 6.0.4 on 2026-04-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('product_price', models.FloatField(null=True)),
                ('product_description', models.TextField(null=True)),
                ('product_qty', models.PositiveIntegerField(null=True)),
                ('product_cat', models.CharField(choices=[('Electric', 'Electric'), ('Cloth', 'Cloth'), ('Food', 'Food')], null=True)),
                ('product_img', models.ImageField(null=True, upload_to='media/product_imgs')),
            ],
        ),
    ]
