# Generated by Django 6.0.4 on 2026-04-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
